before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
- goos:
    - linux
- goarch:
    - amd64
archive:
  replacements:
    linux: Linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
